export default {
  user: "",
  category: [],
  details_login: true,
  showOut: true,
  returnMember: false,
  shopping_Cart: [],
  shopping_Cart1: [],
  shopping_Cart2: [],
  shopping_Cart3:[],
  userData: {},
  receiveAddress: [],
  idOrder: "",
  orderData: {},
  valueObj: 0,
  orderSettleId: [],
  to_orderSettle: false,
  to_orderSettle2: false,
  returnShoppingCart: false,
  isAnonymous: false,
  recentBrowsingData: [],
  cityName: "城市",
  return_Class: false,
  isLocation: false,
  classDataAll: [],
  classDataArr: [],
  tabnumobj: 0,
  isLogin: false
};
