export default {
  user: "",
  category: [],
  details_login: true,
  showOut: false,
  returnMember: false,
  shopping_Cart: [],
  shopping_Cart1: [],
  shopping_Cart2: [],
  userData: {},
  receiveAddress: [],
  idOrder: "",
  orderData: {},
  valueObj: 0,
  orderSettleId: [],
  to_orderSettle: false,
  to_orderSettle2: false,
  returnShoppingCart: false,
  isAnonymous: false,
  recentBrowsingData: [],
  cityName: "成都市"
};
